// LEGACY: PDF export no activo. El flujo actual es HTML para WhatsApp via ExportPlan.ts.
// Este archivo NO está importado en ningún lado. No eliminar sin confirmar con el equipo.
import { StyleSheet } from '@react-pdf/renderer';

export const C = {
  primary: '#0066CC',
  primaryDark: '#004d99',
  navy: '#0D2640',
  deep: '#0D2640',
  green: '#2E9E70',
  accent: '#CC6600',
  orange: '#CC6600',
  red: '#EF4444',
  surface: '#F6F6F6',
  white: '#FFFFFF',
  border: '#d1d5db',
  textPrimary: '#0D2640',
  textSecondary: '#4b5563',
  textTertiary: '#9CA3AF',
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xl2: 32,
  },
  fontSize: {
    xs: 10,
    sm: 11,
    md: 12,
    base: 13,
    lg: 14,
    xl: 16,
    xl2: 18,
    xl3: 20,
    xl4: 28,
    xl5: 32,
  },
};

export const styles = StyleSheet.create({
  page: {
    width: 1080,
    height: 1920,
    paddingTop: 80,
    paddingHorizontal: 36,
    paddingBottom: 60,
    backgroundColor: C.surface,
    fontFamily: 'Inter',
    color: C.navy,
  },
  logoHeader: {
    position: 'absolute',
    top: 24,
    left: 0,
    right: 0,
    height: 60,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 36,
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  logo: {
    width: 120,
    height: 40,
  },
  greeting: {
    fontSize: 32,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  planBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.05)',
    color: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 16,
    fontFamily: 'Inter',
  },
  subtitle: {
    fontSize: 18,
    color: '#6B7280',
    marginBottom: 16,
  },
  nextUpdate: {
    alignSelf: 'flex-start',
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
    marginBottom: 40,
    fontFamily: 'Inter',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Inter',
  },
  card: {
    backgroundColor: C.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 12,
    fontFamily: 'Inter',
  },
  navCard: {
    backgroundColor: C.navy,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
  },
  navCardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  navCardValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginBottom: 4,
  },
  navCardAnterior: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: 700,
  },
  navCardActual: {
    fontSize: 28,
    fontWeight: 800,
    color: C.white,
    fontFamily: 'Inter',
  },
  navCardUnit: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: 700,
  },
  navCardSubtext: {
    fontSize: 12,
    fontWeight: 700,
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  navCardDelta: {
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
  },
  measureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  measureCard: {
    width: 468,
    backgroundColor: C.white,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  measureTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 12,
    marginBottom: 8,
  },
  statAnterior: {
    fontSize: 18,
    color: '#9CA3AF',
    fontWeight: 700,
  },
  statActual: {
    fontSize: 28,
    fontWeight: 800,
    color: C.navy,
    fontFamily: 'Inter',
  },
  statDelta: {
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
  },
  greenCard: {
    backgroundColor: C.green,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
  },
  greenCardTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: 'rgba(255,255,255,0.8)',
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  greenCardValue: {
    fontSize: 28,
    fontWeight: 800,
    color: C.white,
    fontFamily: 'Inter',
  },
  progressBar: {
    height: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 6,
    marginTop: 12,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: C.white,
    borderRadius: 6,
  },
  miniGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  miniCard: {
    width: 228,
    backgroundColor: C.white,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  miniTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  miniValue: {
    fontSize: 22,
    fontWeight: 800,
    color: C.navy,
    fontFamily: 'Inter',
  },
  miniProgress: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    marginTop: 12,
    overflow: 'hidden',
  },
  miniProgressFill: {
    height: '100%',
    backgroundColor: '#0D2640',
    borderRadius: 4,
  },
  macroGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  macroPill: {
    backgroundColor: C.navy,
    color: C.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
  },
  strategyPill: {
    backgroundColor: C.primary,
    color: C.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  exerciseTableContainer: {
    marginBottom: 16,
  },
  exerciseTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.navy,
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
  },
  exerciseTableHeaderCell: {
    color: C.white,
    fontSize: 10,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: 'Inter',
  },
  exerciseTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: C.white,
  },
  exerciseTableRowLast: {
    borderBottomWidth: 0,
  },
  exerciseTableColSerie: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseTableColVideo: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseTableColEjercicio: {
    flex: 1,
    paddingHorizontal: 8,
  },
  exerciseTableColSets: {
    width: 50,
    textAlign: 'center',
  },
  exerciseTableColReps: {
    width: 50,
    textAlign: 'center',
  },
  exerciseTableColTecnica: {
    width: 70,
    textAlign: 'center',
  },
  exerciseTableColRir: {
    width: 40,
    textAlign: 'center',
  },
  exerciseTableColDescanso: {
    width: 70,
    textAlign: 'center',
  },
  exerciseTableColNotas: {
    width: 60,
    textAlign: 'center',
  },
  groupSubHeader: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
  },
  groupSubHeaderText: {
    fontSize: 8,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  exerciseCode: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.navy,
    color: C.white,
    textAlign: 'center',
    lineHeight: 32,
    fontSize: 12,
    fontWeight: 800,
    marginRight: 12,
  },
  exerciseName: {
    flex: 1,
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
  },
  exerciseDetail: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  exerciseBadgeTecnica: {
    fontSize: 11,
    fontWeight: 800,
    marginTop: 2,
  },
  clinicalItem: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  clinicalNumber: {
    fontSize: 14,
    fontWeight: 700,
    color: C.primary,
  },
  clinicalText: {
    flex: 1,
    fontSize: 14,
    color: '#4B5563',
  },
  coverFooterText: {
    fontSize: 18,
    fontWeight: 600,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
  },
  coverDate: {
    fontSize: 12,
    fontWeight: 600,
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    marginTop: 8,
  },
  summarySubtitle: {
    fontSize: 18,
    color: '#6B7280',
    marginBottom: 16,
  },
  summaryNextUpdate: {
    alignSelf: 'flex-start',
    backgroundColor: C.green,
    color: C.white,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 800,
    marginBottom: 40,
  },
  mealCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    gap: 10,
    marginBottom: 12,
  },
  mealCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  mealTimePill: {
    backgroundColor: '#16A34A',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  mealTimeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  mealName: {
    fontSize: 12,
    fontWeight: 700,
    color: '#0D2640',
    flex: 1,
  },
  mealMacros: {
    fontSize: 10,
    fontWeight: 700,
    color: '#0D2640',
  },
  mealMacrosDetail: {
    fontSize: 9,
    color: '#6B7280',
  },
  mealMenuPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  mealMenuText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  mealFoodTable: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 8,
    gap: 3,
  },
  mealFoodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: C.white,
  },
  mealFoodRowLast: {
    borderBottomWidth: 0,
  },
  mealFoodGrams: {
    fontSize: 9,
    color: '#6B7280',
    width: 70,
    textAlign: 'right',
  },
  mealFoodUnit: {
    fontSize: 9,
    color: '#6B7280',
    width: 70,
    textAlign: 'center',
  },
  mealFoodName: {
    fontSize: 9,
    fontWeight: 400,
    color: '#374151',
    flex: 1,
  },
  mealCategoryHeader: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
    borderRadius: 999,
  },
  mealCategoryText: {
    fontSize: 8,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  supplementDayHeader: {
    backgroundColor: C.navy,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
    marginTop: 16,
  },
  supplementDayTitle: {
    color: C.white,
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: 'Inter',
  },
  supplementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  supplementItemLast: {
    borderBottomWidth: 0,
  },
  supplementHorarioPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  supplementHorarioText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  supplementNombre: {
    fontSize: 14,
    fontWeight: 700,
    color: C.deep,
    flex: 1,
  },
  supplementDosis: {
    fontSize: 12,
    color: '#6B7280',
  },
  clinicalSubTitle: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 12,
    marginTop: 16,
    fontFamily: 'Inter',
  },
  clinicalSubTitleFirst: {
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 12,
    fontFamily: 'Inter',
  },
  glossaryCatHeader: {
    backgroundColor: C.deep,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  glossaryCatTitle: {
    color: C.white,
    fontSize: 13,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  glossaryCatCount: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  glossaryCatCountText: {
    color: C.white,
    fontSize: 10,
    fontWeight: 800,
  },
  glossaryItem: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  glossaryItemLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  glossaryTermHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  glossaryTermBadge: {
    backgroundColor: C.deep,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  glossaryTermBadgeText: {
    color: C.white,
    fontSize: 10,
    fontWeight: 800,
  },
  glossaryTermTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 4,
    fontFamily: 'Inter',
  },
  glossaryTermDef: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  glossaryTermBody: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
    marginLeft: 36,
    lineHeight: 1.5,
  },
  glossaryExample: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    marginTop: 6,
    marginLeft: 36,
  },
  glossaryExampleBadge: {
    backgroundColor: C.deep,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  glossaryExampleBadgeText: {
    color: C.white,
    fontSize: 9,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  glossaryExampleText: {
    fontSize: 12,
    color: C.deep,
    flex: 1,
  },
  faqItem: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  faqQuestion: {
    fontSize: 13,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 6,
    fontFamily: 'Inter',
  },
  faqAnswer: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  splitRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  splitCol: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  splitLabel: {
    fontSize: 14,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  splitBody: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  gridItemTitle: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#9CA3AF',
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  columnsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  column: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  columnTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  columnBody: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  guideSection: {
    marginBottom: 20,
  },
  guideSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  guideBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  guideBadgeText: {
    color: C.white,
    fontSize: 11,
    fontWeight: 800,
  },
  guideSectionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: C.deep,
  },
  guideCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  guideCardPrimary: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#0B63CE',
    backgroundColor: '#F0F7FF',
  },
  guideCardSuccess: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#10B981',
    backgroundColor: '#ECFDF5',
  },
  guideCardDanger: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  guideCardTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 8,
  },
  guideCardBody: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  guideSplitRow: {
    flexDirection: 'row',
    gap: 12,
  },
  guideSplitCard: {
    flex: 1,
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  guideSplitLabel: {
    fontSize: 13,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  guideItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 6,
  },
  guideItemText: {
    fontSize: 13,
    color: '#4B5563',
    flex: 1,
  },
  guideChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  guideChip: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  guideChipText: {
    color: '#065F46',
    fontSize: 12,
    fontWeight: 800,
  },
  guideFaqItem: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  guideFaqQuestion: {
    fontSize: 13,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 6,
  },
  guideFaqAnswer: {
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 1.5,
  },
  contactCard: {
    backgroundColor: C.primary,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    marginBottom: 24,
  },
  contactLink: {
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 999,
  },
  contactLinkText: {
    color: C.white,
    fontSize: 11,
    fontWeight: 800,
  },
  blockBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
  },
  blockBadgeText: {
    fontSize: 8,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  exerciseTableRowCell: {
    fontSize: 10,
    fontWeight: 700,
    color: '#0D2640',
  },
  supplementTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.navy,
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
  },
  supplementTableHeaderCell: {
    color: C.white,
    fontSize: 10,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: 'Inter',
  },
  supplementTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: C.white,
  },
  supplementTableRowLast: {
    borderBottomWidth: 0,
  },
  supplementTableColHora: {
    width: 120,
    paddingHorizontal: 8,
  },
  supplementTableColTiempo: {
    width: 120,
    paddingHorizontal: 8,
  },
  supplementTableColNombre: {
    flex: 1,
    paddingHorizontal: 8,
  },
  supplementTableColLink: {
    width: 120,
    paddingHorizontal: 8,
    textAlign: 'center',
  },
  dayLabel: {
    fontSize: 28,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 16,
    fontFamily: 'Inter',
  },
  coverContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 36,
  },
  socialIcons: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 24,
  },
  socialIcon: {
    width: 96,
    height: 96,
    borderRadius: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionDayHeader: {
    backgroundColor: C.navy,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 12,
    marginTop: 16,
  },
  nutritionDayTitle: {
    color: C.white,
    fontSize: 14,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: 'Inter',
  },
  nutritionTableContainer: {
    marginBottom: 24,
  },
  glossaryCat: {
    marginBottom: 16,
  },
  glossaryTerm: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  coverPage: {
    width: 1080,
    height: 1920,
    backgroundColor: C.primary,
    padding: 36,
  },
  coverLogo: {
    width: 480,
    height: 160,
    alignSelf: 'center',
  },
  coverTitle: {
    fontSize: 96,
    fontWeight: 800,
    color: C.white,
    textAlign: 'center',
    fontFamily: 'Inter',
  },
  coverTagline: {
    fontSize: 32,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  guideHeader: {
    backgroundColor: C.navy,
    padding: 24,
    borderRadius: 16,
    marginBottom: 24,
  },
  guideHeaderTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: C.white,
    marginBottom: 4,
    fontFamily: 'Inter',
  },
  guideHeaderSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.7)',
  },
  calendarPage: {
    width: 1080,
    height: 1920,
    paddingTop: 80,
    paddingHorizontal: 36,
    paddingBottom: 60,
    backgroundColor: C.surface,
    fontFamily: 'Inter',
    color: C.navy,
  },
  calendarHeader: {
    fontSize: 24,
    fontWeight: 800,
    color: C.navy,
    marginBottom: 24,
    fontFamily: 'Inter',
  },
  calendarRow: {
    flexDirection: 'row',
    gap: 8,
  },
  calendarCard: {
    flex: 1,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 14,
    minHeight: 160,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  calendarCardContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarDayLabel: {
    fontSize: 10,
    fontWeight: 800,
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    fontFamily: 'Inter',
  },
  calendarDayPill: {
    backgroundColor: C.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 10,
  },
  calendarDayPillText: {
    fontSize: 10,
    fontWeight: 800,
    color: C.white,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    fontFamily: 'Inter',
  },
  calendarActivity: {
    fontSize: 13,
    fontWeight: 700,
    color: C.navy,
    marginBottom: 10,
    lineHeight: 1.3,
    textAlign: 'center',
  },
  calendarMeta: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 4,
    lineHeight: 1.4,
    textAlign: 'center',
  },
  calendarDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 8,
  },
  calendarBadge: {
    alignSelf: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginTop: 8,
  },
  calendarBadgeText: {
    fontSize: 9,
    fontWeight: 700,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  calendarDuration: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 6,
    textAlign: 'center',
  },
  calendarTypeBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginTop: 8,
  },
  calendarTypeBadgeText: {
    fontSize: 9,
    fontWeight: 800,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 36,
    gap: 12,
    zIndex: 1,
  },
  footerDivider: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.12)',
    marginBottom: 4,
  },
  footerLogo: {
    width: 120,
    height: 40,
  },
  footerBrandText: {
    fontSize: 11,
    fontWeight: 700,
    color: '#0D2640',
    textAlign: 'center',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  editorialSection: {
    marginBottom: 28,
    paddingTop: 8,
  },
  editorialSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  editorialBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editorialBadgeText: {
    color: C.white,
    fontSize: 16,
    fontWeight: 800,
  },
  editorialSectionTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: C.deep,
    fontFamily: 'Inter',
    letterSpacing: -0.3,
  },
  editorialCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  editorialCardTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 10,
    fontFamily: 'Inter',
  },
  editorialCardBody: {
    fontSize: 12,
    color: '#374151',
    lineHeight: 1.7,
    fontFamily: 'Inter',
  },
  editorialSplitRow: {
    flexDirection: 'row',
    gap: 16,
  },
  editorialSplitCard: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  editorialSplitLabel: {
    fontSize: 12,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  editorialItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 6,
  },
  editorialItemBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 6,
  },
  editorialItemText: {
    fontSize: 12,
    color: '#374151',
    flex: 1,
    lineHeight: 1.6,
  },
  editorialChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  editorialChip: {
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  editorialChipText: {
    color: '#0D2640',
    fontSize: 11,
    fontWeight: 700,
  },
  editorialHighlightBox: {
    backgroundColor: C.deep,
    padding: 18,
    borderRadius: 16,
  },
  editorialHighlightText: {
    color: C.white,
    fontSize: 13,
    lineHeight: 1.6,
  },
  editorialFaqItem: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  editorialFaqQuestion: {
    fontSize: 13,
    fontWeight: 700,
    color: C.deep,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  editorialFaqAnswer: {
    fontSize: 12,
    color: '#4B5563',
    lineHeight: 1.6,
    fontFamily: 'Inter',
  },
  editorialDangerTag: {
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  editorialDangerText: {
    color: '#DC2626',
    fontSize: 11,
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
